## JVM
org.gradle.jvmargs=-Xmx2560m -XX:MaxMetaspaceSize=640m -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.daemon=true
## 低配机器（2 核）：worker 限制为 1，避免 D8/R8 与 Kotlin 编译争抢内存
org.gradle.workers.max=1

## AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableJetifier=false

## Kotlin
kotlin.code.style=official
kotlin.incremental=true
